Parameters:
  VpcCidrBlock:
    Type: String
    Default: "10.100.0.0/16"
    Description: "Input the VPC CIDR Block"

  Subnet1CidrBlock:
    Type: String
    Default: "10.100.1.0/24"
    Description: "Subnet 1 CIDR Block"


Resources:
  GabiVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VpcCidrBlock

  Subnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: !Ref Subnet1CidrBlock
      AvailabilityZone: !Select [0, !GetAZs]
#        Fn::Select:
#          - 0
#          - Fn::GetAZs: ""
          

